<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\basura.png" />
    <None Remove="Assets\bbdd.png" />
    <None Remove="Assets\botonmas.png" />
    <None Remove="Assets\lapiz.png" />
    <None Remove="Assets\salir.png" />
    <None Remove="Assets\Vector.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.2.0" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\basura.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\bbdd.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\botonmas.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\lapiz.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\salir.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Vector.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
